### ISSUE TITLE
Error while updating property 'endNode' of a view managed by: RNSharedElementTranstion

### ISSUE THREAD

**Issue by julianfrancodev** [IjzerenHein/react-native-shared-element#33] opened 2020-05-25 04:30 UTC
I'm using **react-navigation-shared-element@next react-native-shared-element** and **@react-navigation/native@^5.0.9 @react-navigation/stack@^5.1.1**

![Screenshot_20200524_232842](https://user-images.githubusercontent.com/27922676/82778215-5de55080-9e16-11ea-9cce-73b3f42976cd.png)

I have that error when execute more then 2 times an shared element animation.

![Screenshot_20200524-232237_shop](https://user-images.githubusercontent.com/27922676/82778098-f4654200-9e15-11ea-97ee-5c4265806860.jpg)

Thanks <3

**Comment by IjzerenHein** [comment] 2020-05-25 07:13
Duplicate of #30

**Comment by IjzerenHein** [comment] 2020-05-25 07:14
Which version of react-native and react-native-shared-element are you using?

**Comment by jorgemasta** [comment] 2020-05-25 11:13
Same here with a **Xioami Mi A1** and 
| Library                         | Version |
|---------------------------------|---------|
| react-native                    | 0.61.5  |
| react-navigation                | 4.3.9   |
| react-navigation-shared-element | 2.3.0   |
| react-navigation-stack          | 2.5.1   |
| react-native-shared-element     | 0.7.0   |

**Comment by julianfrancodev** [comment] 2020-05-25 17:16
> Which version of react-native and react-native-shared-element are you using? And on what Android phone (API) are you seeing this?

| Library | Version |
| --- | --- |
| react-navigation-shared-element@next| ^5.0.0-alpha1 |
| react-native-shared-element | ^0.7.0 |

I'm seeing this in  Note 10+ API 29

**Comment by jorgemasta** [comment] 2020-05-28 17:16
I have noticed that I have this problem when I use a `SharedElement` inside a `ListHeaderComponent` of a `FlatList`. Only android.

**Comment by IjzerenHein** [comment] 2020-05-29 06:51
@jorgemasta Thanks for sharing that, that might help 👍

**Comment by IjzerenHein** [comment] 2020-05-29 06:52
I would be awesome if perhaps someone can add a reproduction case to the `./test-app`, that would be really helpful to me and would speed fixing this up 👍

**Comment by ironforward** [comment] 2020-06-15 19:48
i ran into this issue as well, and found it was not the child view that was missing but instead it was the ancestor; after setting `collaspable={false}` on the ancestor view where my ref was, this issue went away.

**Comment by willroyMyles** [comment] 2020-07-11 22:07
I've encountered this problem when the shared element is in a list thats in a tabNavigator thats in a stack navigator 

<Stack_Navigator>
	
	<ViewItemPage>
	
	</ViewItemPage>
	
	<TabNavigator>
		
		<Screen1>

			<List>

				<MySharedElement />

			</List>

		</Screen1>

		<Screen2>

		</Screen2>

	</TabNavigator

</Stack_Navigator>


debugged the call method and saw that otherRoute from createSharedStackNavigator configuration is from TabNavigator page and not the Screen1 page (where is should be called from). the error may be thrown because after the target page is mounted, it cannot find the sharedElement to navigate back to because its not on the TabNavigator page but in the list. 

when the sharedElement is not in a nested tabNavigator, works fine

**Comment by rakhi2104** [comment] 2020-09-12 14:22
I've encountered a similar error, even when I removed the elements out of the nested navigator
![Screenshot_20200912-195021](https://user-images.githubusercontent.com/17671710/92997498-64b4e200-f531-11ea-91fc-e2eafbde14ae.jpg)

**Comment by ducpt2** [comment] 2020-10-15 04:37
+1 i met the same issue when try it with react navigation v5.

**Comment by ducpt2** [comment] 2020-10-15 06:47
hi @ironforward , i am using react-navigation-share-element 5.0.0-alpha1 and met this issue, where i can add collaspable={false} to fix the issue. Thanks

**Comment by flaviolivolsi** [comment] 2020-11-06 17:05
Hi, is there any news about this? Unfortunately I met the same issue with 5.0.0-alpha1 and `collapsable={false}` on the ancestor View doesn't solve it. Thanks!

**Comment by iDuuck** [comment] 2021-01-02 18:47
bum

**Comment by macist-m** [comment] 2021-01-27 22:04
Any info about this still happening... on 5.0.0-alpha1

**Comment by robertohein** [comment] 2021-03-29 19:35
any updates on this?

**Comment by HanifAnnurRahman** [comment] 2021-04-16 06:13
Maybe this will fix the isssue, I extended `createSharedElementStackNavigator.tsx` from `react-navigation-shared-element` v5.0.0-alpha1:
```
import * as React from 'react';
import {
  useNavigationBuilder,
  createNavigatorFactory,
  StackRouter,
  DefaultNavigatorOptions,
  RouteConfig,
  StackRouterOptions,
  StackNavigationState,
} from '@react-navigation/native';
import {
  CardAnimationContext,
  StackView,
  StackNavigationOptions,
} from '@react-navigation/stack';
import {SharedElementRendererProxy} from 'react-navigation-shared-element/lib/module/SharedElementRendererProxy';
import SharedElementRendererContext from 'react-navigation-shared-element/lib/module/SharedElementRendererContext';
import SharedElementRendererView from 'react-navigation-shared-element/lib/module/SharedElementRendererView';
import SharedElementRendererData from 'react-navigation-shared-element/lib/module/SharedElementRendererData';
import createSharedElementScene from 'react-navigation-shared-element/lib/module/createSharedElementScene';
import {
  SharedElementSceneComponent,
  SharedElementsComponentConfig,
} from 'react-navigation-shared-element/lib/module/types';
import {
  StackNavigationConfig,
  StackNavigationEventMap,
} from '@react-navigation/stack/lib/typescript/src/types';

let _navigatorId = 1;

export default function createSharedElementStackNavigator<
  ParamList extends Record<string, object | undefined>
>(options?: { name?: string }) {
  const navigatorId =
    options && options.name ? options.name : `stack${_navigatorId}`;
  _navigatorId++;

  const rendererDataProxy = new SharedElementRendererProxy();

  type Props = DefaultNavigatorOptions<StackNavigationOptions> &
    StackRouterOptions &
    StackNavigationConfig;

  function SharedElementStackNavigator({
    initialRouteName,
    children,
    screenOptions,
    ...rest
  }: Props) {
    const { state, descriptors, navigation } = useNavigationBuilder<
      StackNavigationState,
      StackRouterOptions,
      StackNavigationOptions,
      StackNavigationEventMap
    >(StackRouter, {
      initialRouteName,
      children,
      screenOptions,
    });

    const rendererDataRef = React.useRef<SharedElementRendererData | null>(
      null
    );
    
    const transitionDuration = 400;
    const [shouldShowTransition, setShouldShowTransition] = React.useState(false);
    React.useEffect(() => {
      setShouldShowTransition(true);
      // set shouldShowTransition to false after transition has ended
      setTimeout(() => {
        setShouldShowTransition(false);
      }, transitionDuration)
    }, [state])

    return (
      <SharedElementRendererContext.Consumer>
        {rendererData => {
          // In case a renderer is already present higher up in the chain
          // then don't bother creating a renderer here, but use that one instead
          if (!rendererData) {
            rendererDataRef.current =
              rendererDataRef.current || new SharedElementRendererData();
            rendererDataProxy.source = rendererDataRef.current;
          } else {
            rendererDataProxy.source = rendererData;
          }
          return (
            <SharedElementRendererContext.Provider value={rendererDataProxy}>
              <StackView
                {...rest}
                state={state}
                navigation={navigation}
                descriptors={descriptors}
              />
              {rendererDataRef.current && shouldShowTransition ? (
                <SharedElementRendererView
                  rendererData={rendererDataRef.current}
                />
              ) : (
                undefined
              )}
            </SharedElementRendererContext.Provider>
          );
        }}
      </SharedElementRendererContext.Consumer>
    );
  }

  const navigatorFactory = createNavigatorFactory<
    StackNavigationState,
    StackNavigationOptions,
    StackNavigationEventMap,
    typeof SharedElementStackNavigator
  >(SharedElementStackNavigator);

  const { Navigator, Screen } = navigatorFactory<ParamList>();

  type ScreenProps<RouteName extends keyof ParamList> = Omit<
    RouteConfig<
      ParamList,
      RouteName,
      StackNavigationState,
      StackNavigationOptions,
      StackNavigationEventMap
    >,
    'component' | 'children'
  > & {
    component: SharedElementSceneComponent;
    sharedElementsConfig?: SharedElementsComponentConfig;
  };

  function wrapComponent(component: SharedElementSceneComponent) {
    return createSharedElementScene(
      component,
      rendererDataProxy,
      CardAnimationContext,
      navigatorId
    );
  }

  // Wrapping Screen to explicitly statically type a "Shared Element" Screen.
  function wrapScreen<RouteName extends keyof ParamList>(
    _: ScreenProps<RouteName>
  ) {
    return null;
  }

  type NavigatorProps = React.ComponentProps<typeof Navigator>;

  function getSharedElementsChildrenProps(children: React.ReactNode) {
    return React.Children.toArray(children).reduce<any[]>((acc, child) => {
      if (React.isValidElement(child)) {
        if (child.type === wrapScreen) {
          acc.push(child.props);
        }

        if (child.type === React.Fragment) {
          acc.push(...getSharedElementsChildrenProps(child.props.children));
        }
      }
      return acc;
    }, []);
  }

  // react-navigation only allows the Screen component as direct children
  // of Navigator, this is why we need to wrap the Navigator
  function WrapNavigator(props: NavigatorProps) {
    const { children, ...rest } = props;
    const componentMapRef = React.useRef<Map<any, any>>(new Map());
    const screenChildrenProps = getSharedElementsChildrenProps(children);

    return (
      <Navigator {...rest}>
        {screenChildrenProps.map(
          ({ component, sharedElementsConfig, ...childrenProps }) => {
            if (sharedElementsConfig)
              component.sharedElements = sharedElementsConfig;

            if (!componentMapRef.current.has(component)) {
              componentMapRef.current.set(component, wrapComponent(component));
            }

            const wrappedComponent = componentMapRef.current.get(component);

            return (
              <Screen
                key={childrenProps.name}
                {...childrenProps}
                component={wrappedComponent}
              />
            );
          }
        )}
      </Navigator>
    );
  }

  return {
    Navigator: WrapNavigator,
    Screen: wrapScreen,
  };
}
```
I added code below to `createSharedElementStackNavigator.tsx`:
```
const transitionDuration = 400;
const [shouldShowTransition, setShouldShowTransition] = React.useState(false);
React.useEffect(() => {
  setShouldShowTransition(true);
  // set shouldShowTransition to false after transition has ended
  setTimeout(() => {
    setShouldShowTransition(false);
  }, transitionDuration)
}, [state])
...
{rendererDataRef.current && shouldShowTransition ? (
  <SharedElementRendererView
    rendererData={rendererDataRef.current}
  />
) : (
  undefined
)}
```
and change `transitionDuration` to appropriate value.

Basically, I tried to make sure the node is already created when `RNSharedElementTranstion` trying to resolve the node or view. I do this by mounting `SharedElementRendererView` (which contains `SharedElementTransition`) after react navigation state is changed, and then unmount it after screen transition has ended, so on the next state change, it in unmounted state. It seems fix the issue, I already tested it on Samsung Galaxy Tab A 8.0 (2019) with android version 9.

**Comment by LaurenceM10** [comment] 2021-05-30 07:19
Same issue here in debug mode on Android. Is not happening always.

**Comment by p-syche** [comment] 2023-01-26 12:17
Thank you @gigadeplex for your comment.
Given how long this issue has been inactive I'm closing it as stale.

**Closed by p-syche** 2023-01-26 12:17 UTC
Labels: bug, duplicate, android
