### ISSUE TITLE
shared element is on top of another element

### ISSUE THREAD

**Issue by arasrezaei** [IjzerenHein/react-native-shared-element#41] opened 2020-10-02 15:45 UTC
hi there,
I do not know this is a issue or not,
but i have problem to fix this issue:
![untitled](https://user-images.githubusercontent.com/36116677/94942759-96431c80-04e3-11eb-9743-e9a8099b390e.gif)
I tried zIndex but it's not working cause the transitioning element is on top of others,
and after fading/removing actual element shows.
is there any walkaround for fixing this?

**Comment by IjzerenHein** [comment] 2021-08-16 13:37
Hi! The shared elements are always rendered on top. If you want other elements to be rendered on top, then you need to wrap these with `<SharedElement>` as well and tell the `sharedElements` function to use a "fade" transition on these.

Please have a look at the "OverlappingElements" example in the react-navigation-shared-elements example app:
https://github.com/IjzerenHein/react-navigation-shared-element/tree/main/example

In the example the DetailScreen wraps all elements in `<SharedElement>` that overlay the image. This allows the shared-element library to render these elements on top of the image. Next, return these elements (`topOverlay` and `bottomOverlay`) in the `sharedElements` function. The order of this function, is also the z-ordering at which they are rendered. By using `animation: 'fade'`, these elements will be fade-in and out when the scene becomes visible.

**Comment by p-syche** [comment] 2022-06-19 23:16
Hello @arasrezaei !
My name is Aleks, I'm helping out with maintenance in this repo. 

I am closing the issue you opened, because the situation you described was not a bug. Maybe you could find the time to add something to the library documentation to describe the animations you wanted to implement and the solution provided by @IjzerenHein ?

**Closed by p-syche** 2022-06-19 23:16 UTC
