### ISSUE TITLE
Clicking the navigation to and from results in error

### ISSUE THREAD

**Issue by jithinlal** [IjzerenHein/react-native-shared-element#22] opened 2020-03-19 18:02 UTC
I am getting the following error when switching between screens.

The correct instance could not be fetched but here goes the error.
```

Error while updating property 'endNode' of a view managed by: RNSharedElementTransition

null

Trying to resolve view with a tag 3419 which doesn't exist
```

Once I dismiss the error a faded image of the shared element remains

**Comment by IjzerenHein** [comment] 2020-03-29 17:41
Hi 👋 I've transferred the issue here as this is a native error. Could you provide me with an example on how to reproduce this?

**Comment by IjzerenHein** [comment] 2020-04-26 10:21
Closing due to inactivity

**Closed by IjzerenHein** 2020-04-26 10:21 UTC
Labels: android, bug, needs repro

**Comment by jithinlal** [comment] 2020-04-30 10:28
This error is not resolved, this come with randomly when switching one page to other

**Comment by xiendong** [comment] 2020-05-08 04:24
Hello, I have the same problem, and it shows up on the Play Store pre-launch report as a crash failure. Here's the stack trace, but not sure if it will help. Thanks!

```
com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'endNode' of a view managed by: RNSharedElementTransition
	at com.facebook.react.uimanager.na$j.a()
	at com.facebook.react.uimanager.ka$b.a()
	at com.facebook.react.uimanager.ka.a()
	at com.facebook.react.uimanager.ViewManager.updateProperties()
	at com.facebook.react.uimanager.m.a()
	at com.facebook.react.uimanager.da$c.execute()
	at com.facebook.react.uimanager.da$g.c()
	at com.facebook.react.uimanager.da$g.b()
	at com.facebook.react.uimanager.c.a()
	at com.facebook.react.modules.core.i$b.a()
	at com.facebook.react.modules.core.a.doFrame()
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:869)
	at android.view.Choreographer.doCallbacks(Choreographer.java:683)
	at android.view.Choreographer.doFrame(Choreographer.java:616)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	... 22 more
Caused by: com.facebook.react.uimanager.e: Trying to resolve view with tag 933 which doesn't exist
	at com.facebook.react.uimanager.m.b()
	at com.ijzerenhein.sharedelement.RNSharedElementTransitionManager.setViewItem()
	at com.ijzerenhein.sharedelement.RNSharedElementTransitionManager.setEndNode()
	... 23 more
```

**Comment by IjzerenHein** [comment] 2020-05-08 07:24
Do you have any idea how to reproduce this? Please share how you are using it, which libs, versions, android version.

**Comment by xseignard** [comment] 2020-05-08 07:57
Same problem here, happens randomly.

Here is the output of `react-native info`:
```
info Fetching system and libraries information...
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 114.24 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242 - /usr/bin/javac
    Python: 2.7.10 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found
```

Testing on readmi note 7, android `9 PKQ1.180904.001` 

Relevant lib versions:
```json
"@react-navigation/drawer": "^5.4.1",
"@react-navigation/native": "^5.1.5",
"@react-navigation/stack": "^5.2.13",
"react-native-shared-element": "^0.7.0",
"react-navigation-shared-element": "^5.0.0-alpha1",
"react-native-fast-image": "^8.1.5",
```

Screen conf:
```jsx
<Stack.Screen
  name="Manifestation"
  component={Manifestation}
  options={({ route }) => ({
    headerShown: false,
    title: route.params.title,
    cardStyleInterpolator({ current: { progress } }) {
      return {
        cardStyle: {
          opacity: progress,
          transform: [
            {
              translateY: progress.interpolate({
                inputRange: [0, 1],
                outputRange: [50, 0],
              }),
            },
          ],
        },
      }
    },
  })}
  sharedElementsConfig={(route, otherRoute, showing) => {
    const { id } = route.params
    return [`manifestation.${id}.image`]
  }}
/>
```

And shared elements:
```jsx
<TouchableOpacity
  onPress={() =>
    navigation.push('Manifestation', {
      id: manifestation.id,
      title: manifestation.title,
    })
  }
  activeOpacity={0.5}
>
  <SharedElement id={`manifestation.${manifestation.id}.image`}>
    <FastImage
      style={[
        styles.image,
        { width: cardHeight, height: cardHeight },
      ]}
      source={{
        uri: `https://XXXXX/${manifestation.image}`,
        priority: FastImage.priority.high,
      }}
      resizeMode={FastImage.resizeMode.cover}
    />
  </SharedElement>
</TouchableOpacity>
```

AND

```jsx
<SharedElement id={`manifestation.${manifestation.id}.image`}>
  <FastImage
    style={styles.image}
    source={{
      uri: `https://XXXXX/${manifestation.image}`,
      priority: FastImage.priority.high,
    }}
    resizeMode={FastImage.resizeMode.cover}
  />
</SharedElement>
```

Hope this helps, let me know if you need more informations.

And thanks for this cool lib 👍

**Comment by IjzerenHein** [comment] 2020-05-08 08:56
Thanks for the info!

**Comment by ducpt2** [comment] 2020-10-15 04:41
+1 i met the same issue. 
Thanks for the greate lib.

**Comment by macist-m** [comment] 2021-01-28 21:10
Any idea how to resolve this? Thanks...

**Comment by jonathanroze** [comment] 2021-06-27 08:29
Any updates about that issue ?
