### ISSUE TITLE
SharedElements not displaying during transitions

### ISSUE THREAD

**Issue by kdo1234** [IjzerenHein/react-native-shared-element#44] opened 2020-11-19 03:51 UTC
During about 10% of the transitions in my app some of the SharedElements in the transition don't display during the transition. The issue seems to be non deterministic. None of the SharedElement components are images. They are View, Text, react-native-vector-icons and react-native-linear-gradient.

Also, I've found that I'm able to create SharedElement HOCs that contain ~20 views that consistently render properly during transitions, but at around ~40 elements only part of the HOC renders properly during the transition

Does anyone have any advice on how to debug this?

I can reproduce this in release mode on an iPhone X, ios 14.2 and with react-native 0.63.2 and react-native-shared-element 0.7.0

Thank you for any advice.

**Comment by IjzerenHein** [comment] 2021-08-16 11:06
In order to investigate that, I'll need a reproducible demo. Please add a use-case to the `./example` app that exhibits this problem.

It's possible though that you are trying to animate too much and the phone simply cannot handle it

**Comment by p-syche** [comment] 2022-06-19 23:12
I am closing this issue, since it was opened a year and a half ago and the author has not provided a reproducible demo.

@kdo1234 - if you are still facing the same problem please open a new issue with a reproducible demo, thank you!

**Closed by p-syche** 2022-06-19 23:12 UTC
Labels: needs repro
