### ISSUE TITLE
borderRadius missing on image transition

### ISSUE THREAD

**Issue by russcampbell** [IjzerenHein/react-native-shared-element#40] opened 2020-09-24 20:17 UTC
I'm on version 0.70 and images are missing their border radius during transition. It seems this has been resolved before but it's not working for me. Thanks.

**Comment by jonesaustindev** [comment] 2020-10-30 20:03
@russcampbell did you find a solution to this? I'm seeing this on Android but not iOS.

**Comment by ArekChr** [comment] 2020-11-05 08:52
+1

**Comment by shahood-hussain** [comment] 2020-11-10 15:18
try adding resizeMode on image. I got a fix with that

**Comment by jonesaustindev** [comment] 2020-11-10 15:24
This styling I have below allowed the border radius to work correctly on Android during the transition
```
height: 95,
width: 95,
borderRadius: 500,
resizeMode: 'cover',
```

**Comment by IjzerenHein** [comment] 2021-08-16 10:41
Duplicate of #51 (which contained more detailed info)

Please have a look at the answer provided here:
https://github.com/IjzerenHein/react-native-shared-element/issues/51#issuecomment-899407879

**Closed by IjzerenHein** 2021-08-16 10:41 UTC
