### ISSUE TITLE
Maximum update depth exceeded

### ISSUE THREAD

**Issue by mfbx9da4** [IjzerenHein/react-native-shared-element#94] opened 2022-02-21 09:14 UTC
Just refactoring the basic example to extract scene 2 into a separate component leads to a recursive update and a react error `Maximum update depth exceeded`. The line which is causing this error is

```
        ref={props.onSetScene2Ref}
```

Which in turn calls 
```
 this.setState({ scene2Ancestor: nodeFromRef(ref) })
```

The ref seems to be alternating between `null` and a defined ref value but not sure why. Any suggestions what to try?

```jsx
import * as React from 'react'
import { View, StyleSheet, Animated, Dimensions, TouchableOpacity, Image } from 'react-native'
import { SharedElement, SharedElementTransition, nodeFromRef } from 'react-native-shared-element'

export class Example extends React.Component {
  state = {
    progress: new Animated.Value(0),
    isScene2Visible: false,
    isInProgress: false,
    scene1Ancestor: null,
    scene1Node: null,
    scene2Ancestor: null,
    scene2Node: null,
  }

  onPressNavigate = () => {
    this.setState({ isScene2Visible: true, isInProgress: true })
    Animated.timing(this.state.progress, {
      toValue: 1,
      duration: 1000,
      useNativeDriver: true,
    }).start(() => this.setState({ isInProgress: false }))
  }

  onPressBack = () => {
    this.setState({ isInProgress: true })
    Animated.timing(this.state.progress, {
      toValue: 0,
      duration: 1000,
      useNativeDriver: true,
    }).start(() => this.setState({ isScene2Visible: false, isInProgress: false }))
  }

  onSetScene1Ref = (ref: View | null) => {
    this.setState({ scene1Ancestor: nodeFromRef(ref) })
  }

  onSetScene2Ref = (ref: View | null) => {
    this.setState({ scene2Ancestor: nodeFromRef(ref) })
  }

  render() {
    const { state } = this
    const { width } = Dimensions.get('window')
    return (
      <>
        <TouchableOpacity
          style={{ flex: 1, backgroundColor: '#ecf0f1' }}
          activeOpacity={0.5}
          onPress={state.isScene2Visible ? this.onPressBack : this.onPressNavigate}
        >
          {/* Scene 1 */}
          <Animated.View
            style={{
              ...StyleSheet.absoluteFillObject,
            }}
          >
            <View
              style={{
                ...StyleSheet.absoluteFillObject,
                backgroundColor: 'white',
                justifyContent: 'center',
                alignItems: 'center',
              }}
              ref={this.onSetScene1Ref}
            >
              <SharedElement onNode={node => this.setState({ scene1Node: node })}>
                <Image style={styles.image1} source={require('./logo.png')} />
              </SharedElement>
            </View>
          </Animated.View>

          {/* Scene 2 */}
          {state.isScene2Visible ? (
            <Scene2
              progress={state.progress}
              onSetScene2Ref={this.onSetScene2Ref.bind(this)}
              setState={this.setState.bind(this)}
            />
          ) : undefined}
        </TouchableOpacity>

        {/* Transition overlay */}
        {state.isInProgress ? (
          <View style={styles.sharedElementOverlay} pointerEvents="none">
            <SharedElementTransition
              start={{
                node: state.scene1Node,
                ancestor: state.scene1Ancestor,
              }}
              end={{
                node: state.scene2Node,
                ancestor: state.scene2Ancestor,
              }}
              debug
              position={state.progress}
              animation="move"
              resize="auto"
              align="auto"
            />
          </View>
        ) : undefined}
      </>
    )
  }
}

function Scene2(props: any) {
  return (
    <Animated.View
      style={{
        ...StyleSheet.absoluteFillObject,
        opacity: props.progress,
      }}
    >
      <View
        style={{
          ...StyleSheet.absoluteFillObject,
          backgroundColor: '#00d8ff',
          justifyContent: 'center',
          alignItems: 'center',
        }}
        ref={props.onSetScene2Ref}
      >
        <SharedElement onNode={node => props.setState({ scene2Node: node })}>
          <Image style={styles.image2} source={require('./logo.png')} />
        </SharedElement>
      </View>
    </Animated.View>
  )
}

const styles = StyleSheet.create({
  image1: {
    resizeMode: 'cover',
    width: 160,
    height: 160,
    // Images & border-radius have quirks in Expo SDK 35/36
    // Uncomment the next line when SDK 37 has been released
    //borderRadius: 80
  },
  image2: {
    resizeMode: 'cover',
    width: 300,
    height: 300,
    borderRadius: 0,
  },
  sharedElementOverlay: {
    ...StyleSheet.absoluteFillObject,
  },
})
```

**Comment by p-syche** [comment] 2022-06-19 23:51
Hello @mfbx9da4 !

Thanks for opening the issue.
I created an Expo Snack based on the code snippet you added: https://snack.expo.dev/@p-syche/upbeat-toffee---rn-shared-element

I can reproduce the issue you described in that snack. I will try to think of a solution in the next few days.

**Comment by SashaMihalache** [comment] 2022-07-14 05:54
Hello @p-syche,

Any news on this?

**Comment by p-syche** [comment] 2022-07-15 09:04
Hello @mfbx9da4 and @SashaMihalache !

I finally got around into looking a little bit deeper into this issue.
It is not specifically a react-shared-element issue, but a ReactJS usage issue. As you may notice the example posted by @SashaMihalache has the second scene inside the main component - that's why everything is working. The example provided by @mfbx9da4 splits up the components.
When passing values between parents and children in React you need to make sure not to directly change state, as it will cause re-renders of the parent, which will cause re-renders of the child, which causes a re-render of parent... you get it ;)

I added a new function called `setNodeInChild`, which is bound to the state in the parent and that's what we should be passing to the child. Once this is set up there's no more React error. You can find the updated Snack here: https://snack.expo.dev/@p-syche/upbeat-toffee---rn-shared-element---fixed

Since this is not a react-native-shared-element issue I am closing it. However you are very welcome to post a PR with a documentation update where you could explain how to use the library with parent/child components.

**Closed by p-syche** 2022-07-15 09:04 UTC
Labels: repro provided

**Comment by p-syche** [comment] 2022-07-15 09:58
@mfbx9da4 well, that's interesting 🤓 

It seems the error was in a different spot 😅 
Try changing line 112:
```
onSetScene2Ref={this.onSetScene2Ref}
```

to 
```
onSetScene2Ref={this.onSetScene2Ref.bind(this)}
```


This looks like it's making the issue come back. Which confirms that this is a React usage issue and not `react-native-shared-element` issue. However it's a slightly different issue from what I thought first 🤷  😅
